"""Initial migration

Revision ID: a4d992a31812
Revises: 
Create Date: 2023-04-16 23:15:27.887026

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4d992a31812'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=280), nullable=False),
    sa.Column('description', sa.String(length=280), nullable=False),
    sa.Column('location', sa.String(length=280), nullable=False),
    sa.Column('city', sa.String(length=280), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('numPlayers', sa.Integer(), nullable=False),
    sa.Column('ongoing', sa.Boolean(), nullable=False),
    sa.Column('sport', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_admin', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=30), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('email', sa.String(length=30), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('matches')
    # ### end Alembic commands ###
